/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AVL_Arbol_Binario;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class Vista_AVL extends javax.swing.JFrame {

    /**
     * Creates new form Vista_AVL
     */
    private avl avl;
    private Graphics arbol;
    private int x, y, x2, y2;
    public Vista_AVL() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.avl = new avl();
        arbol = this.pnlGrafico.getGraphics();
        x = pnlGrafico.getWidth() / 2;
        y = pnlGrafico.getHeight() / 20;
        x2 = pnlGrafico.getWidth() / 10;
        y2 = pnlGrafico.getHeight() / 10;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlGrafico = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        btnGenerarRandom = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAltura = new javax.swing.JButton();
        btnContarNodos = new javax.swing.JButton();
        btnNodosPrimos = new javax.swing.JButton();
        btnNodosHojas = new javax.swing.JButton();
        btnPreOrden = new javax.swing.JButton();
        btnInOrden = new javax.swing.JButton();
        btnPosOrden = new javax.swing.JButton();
        btnPeso = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCamino = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRepaint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        pnlGrafico.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1105, Short.MAX_VALUE)
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnGenerarRandom.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerarRandom.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnGenerarRandom.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarRandom.setText("GenerarRandom");
        btnGenerarRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRandomActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar Grafico");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAltura.setBackground(new java.awt.Color(0, 0, 0));
        btnAltura.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnAltura.setForeground(new java.awt.Color(255, 255, 255));
        btnAltura.setText("Altura");
        btnAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlturaActionPerformed(evt);
            }
        });

        btnContarNodos.setBackground(new java.awt.Color(0, 0, 0));
        btnContarNodos.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnContarNodos.setForeground(new java.awt.Color(255, 255, 255));
        btnContarNodos.setText("Contar Nodos");
        btnContarNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarNodosActionPerformed(evt);
            }
        });

        btnNodosPrimos.setBackground(new java.awt.Color(0, 0, 0));
        btnNodosPrimos.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnNodosPrimos.setForeground(new java.awt.Color(255, 255, 255));
        btnNodosPrimos.setText("Nodos Primos");
        btnNodosPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNodosPrimosActionPerformed(evt);
            }
        });

        btnNodosHojas.setBackground(new java.awt.Color(0, 0, 0));
        btnNodosHojas.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnNodosHojas.setForeground(new java.awt.Color(255, 255, 255));
        btnNodosHojas.setText("Nodos Hojas");
        btnNodosHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNodosHojasActionPerformed(evt);
            }
        });

        btnPreOrden.setBackground(new java.awt.Color(0, 0, 0));
        btnPreOrden.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnPreOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnPreOrden.setText("PreOrden");
        btnPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrdenActionPerformed(evt);
            }
        });

        btnInOrden.setBackground(new java.awt.Color(0, 0, 0));
        btnInOrden.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnInOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnInOrden.setText("InOrden");
        btnInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrdenActionPerformed(evt);
            }
        });

        btnPosOrden.setBackground(new java.awt.Color(0, 0, 0));
        btnPosOrden.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnPosOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnPosOrden.setText("PosOrden");
        btnPosOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosOrdenActionPerformed(evt);
            }
        });

        btnPeso.setBackground(new java.awt.Color(0, 0, 0));
        btnPeso.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnPeso.setForeground(new java.awt.Color(255, 255, 255));
        btnPeso.setText("Peso");
        btnPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesoActionPerformed(evt);
            }
        });

        btnGenerar.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerar.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Genera Arbol predefinido");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Genera un arbol de tamaño ingresado");

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("Dato:");

        btnCamino.setBackground(new java.awt.Color(0, 0, 0));
        btnCamino.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnCamino.setForeground(new java.awt.Color(255, 255, 255));
        btnCamino.setText("Camino mas corto:");
        btnCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminoActionPerformed(evt);
            }
        });

        btnInsertar.setBackground(new java.awt.Color(0, 0, 0));
        btnInsertar.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel7.setText("RECORRIDOS: ");

        btnRepaint.setBackground(new java.awt.Color(0, 0, 0));
        btnRepaint.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnRepaint.setForeground(new java.awt.Color(255, 255, 255));
        btnRepaint.setText("Repaint");
        btnRepaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepaintActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Eliminar Nodo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnGenerarRandom)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNodosPrimos)
                            .addComponent(btnContarNodos)
                            .addComponent(btnBuscar)
                            .addComponent(btnNodosHojas)
                            .addComponent(btnAltura)
                            .addComponent(btnGenerar)
                            .addComponent(jLabel1)
                            .addComponent(btnEliminar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnInsertar)
                                .addGap(18, 18, 18)
                                .addComponent(btnRepaint))
                            .addComponent(btnInOrden)
                            .addComponent(btnCamino)
                            .addComponent(btnPeso)
                            .addComponent(jLabel7)
                            .addComponent(btnPreOrden)
                            .addComponent(btnPosOrden)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsertar)
                    .addComponent(btnRepaint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarRandom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContarNodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNodosPrimos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNodosHojas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAltura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPosOrden)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRandomActionPerformed
        // TODO add your handling code here:
        try {
            avl = new avl();
            arbol = this.pnlGrafico.getGraphics();

            int cantidad = Integer.parseInt(txtCantidad.getText());
            int numero;
            for (int i = 0; i < cantidad; i++) {
                //genera nums aleatorios desde el -10 al 20
                numero = (int) (Math.random() * 99 + 50);
                avl.insertar(numero);
            }
            graficarArbol(arbol, avl.getRaiz(), x, y, x2, y2, 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnGenerarRandomActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.pnlGrafico.repaint();
        avl = new avl();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            int datoBuscar=Integer.parseInt(txtCantidad.getText());
            nodo encontrado=avl.Buscar2(datoBuscar);
            if(encontrado!=null){
                JOptionPane.showMessageDialog(null, "Dato encontrado");
            }else{
                JOptionPane.showMessageDialog(null, "No existe el nodo");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlturaActionPerformed
        // TODO add your handling code here:
        int altura=avl.altura(avl.getRaiz());
        JOptionPane.showMessageDialog(null, altura);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnAlturaActionPerformed

    private void btnContarNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarNodosActionPerformed
        // TODO add your handling code here:
        String cantNodos=avl.Nodos();
        JOptionPane.showMessageDialog(null, cantNodos);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnContarNodosActionPerformed

    private void btnNodosPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNodosPrimosActionPerformed
        // TODO add your handling code here:
        String primos=avl.nodosPrimos();
        JOptionPane.showMessageDialog(null, "Arbol 1: Los nodos que contienen numeros primos son: "+primos);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnNodosPrimosActionPerformed

    private void btnNodosHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNodosHojasActionPerformed
        // TODO add your handling code here:
        String hojas=avl.nodosHojas();
        JOptionPane.showMessageDialog(null, hojas);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnNodosHojasActionPerformed

    private void btnPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrdenActionPerformed
        // TODO add your handling code here:
        String preorden=avl.preOrden();
        JOptionPane.showMessageDialog(null, "El recorrido en PreOrden del Arbol 1 es: "+preorden);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnPreOrdenActionPerformed

    private void btnInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrdenActionPerformed
        // TODO add your handling code here:
        String inorden=avl.InOrden();
        JOptionPane.showMessageDialog(null, "El recorrido en InOrden es: "+inorden);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnInOrdenActionPerformed

    private void btnPosOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosOrdenActionPerformed
        // TODO add your handling code here:
        String postorden=avl.PosOrden();
        JOptionPane.showMessageDialog(null, "El recorrido en PostOrden es: "+postorden);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnPosOrdenActionPerformed

    private void btnPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesoActionPerformed
        // TODO add your handling code here:
        String peso=avl.ramaPeso();
        JOptionPane.showMessageDialog(null, "Arbol: \n"+peso);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnPesoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        try {
            avl = new avl();
            arbol = this.pnlGrafico.getGraphics();
            //se insertan elementos
            avl.insertar(12);
            avl.insertar(6);
            avl.insertar(2);
            avl.insertar(32);
            avl.insertar(-10);
            avl.insertar(108);

            graficarArbol(arbol, avl.getRaiz(), x, y, x2, y2, 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminoActionPerformed
        // TODO add your handling code here:
        try{
            int datoBuscar=Integer.parseInt(txtCantidad.getText());
            String camino=avl.caminoCorto(datoBuscar);
            JOptionPane.showMessageDialog(null, camino);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnCaminoActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        try{
            int dato=Integer.parseInt(txtCantidad.getText());
            avl.insertar(dato);

            Graphics arbol= this.pnlGrafico.getGraphics();

            graficarArbol(arbol, avl.getRaiz(), x, y, x2, y2, 1);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnRepaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepaintActionPerformed
        // TODO add your handling code here:
        this.pnlGrafico.repaint();
    }//GEN-LAST:event_btnRepaintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

        private void graficarArbol(Graphics arbol, nodo raiz, int x, int y, int auxX, int auxY, int nivel){
        
        if (raiz!= null) {
            //graficando las lineas
            arbol.setColor(Color.BLACK);
            if (raiz.izq != null) {
                arbol.drawLine(x, y, x - auxX + (nivel * 2), y + auxY);
            }
            if (raiz.der != null) {
                arbol.drawLine(x, y, x + auxX - (nivel * 2), y + auxY);
            }
            //graficando
            arbol.setColor(Color.YELLOW);
            arbol.fillOval(x - 10, y - 20, 40, 40);
            arbol.setColor(Color.BLACK);
            arbol.drawString(String.valueOf(raiz.info), x, y);

            //recursividad
            graficarArbol(arbol, raiz.izq, x - auxX, y + auxY, auxX + nivel * 2, auxY * 2, nivel + 2);
            graficarArbol(arbol, raiz.der, x + auxX, y + auxY, auxX - nivel * 2, auxY, nivel + 1);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_AVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_AVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_AVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_AVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_AVL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltura;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCamino;
    private javax.swing.JButton btnContarNodos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGenerarRandom;
    private javax.swing.JButton btnInOrden;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnNodosHojas;
    private javax.swing.JButton btnNodosPrimos;
    private javax.swing.JButton btnPeso;
    private javax.swing.JButton btnPosOrden;
    private javax.swing.JButton btnPreOrden;
    private javax.swing.JButton btnRepaint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlGrafico;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
